# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bcAtQ7x60q6ao9Io9m57uNhwWs3HQz7Z
"""

#Creació d'una cadena
'''
Una cadena és text
Es defineix amb cometes simples o dobles
El tipus de dada (str)
'''
message = "Hello"
print(message)

#Operacions bàsiques amb cadenes
'''
+++++++++++++++++++++++++++++++++++
Concatenació (+)
Tasca: Unir cadenes de text
Observació: Hem de conventir els números a text amb str()
+++++++++++++++++++++++++++++++++++
'''
user_name = "Dani"
age = 1987
text = "Hola " + user_name + ", vas nèixer " + str(age)
print(text)
'''Opció amb f string'''
print(f"Hola {user_name}, vas nèixer {age}")

'''
+++++++++++++++++++++++++++++++++++
Repetició (*)
Tasca: Repetir una cadena un nombre determinat de vegades
+++++++++++++++++++++++++++++++++++
'''
print("*" * 10)
print("A" * 3)

'''
+++++++++++++++++++++++++++++++++++
Longitud (len())
Tasca: Saber quants caràcters té una cadena
Observació: Els espais comptent
+++++++++++++++++++++++++++++++++++
'''
manga = "One piece"
print("Longitud de la paraula: " + str(len(manga)))
print(f"Longitud de la paraula 'Uzumaki Naruto' {len("Uzumaki Naruto")} caràcters")

'''
+++++++++++++++++++++++++++++++++++
Accés als caràcters
Tasca: Accedir a caràcters concrets de la cadena de text
Observació:
Les cadenes comencen amb l'índex 0
Accéss positiu (de 0 a len(paraula)) i negatiu (de len(paraula) a 0)
+++++++++++++++++++++++++++++++++++
'''
anime = "Kimetsu No Yaiba"
print(f"Caràcter de la paraula '{anime}' a la primera posició: {anime[0]}");
print(f"Caràcter de la paraula '{anime}' a la posició 2: {anime[2]}");
print(f"Caràcter de la paraula '{anime}' a l'última posició: {anime[-1]}");
print(f"Caràcter de la paraula '{anime}' a l'antepenúltima posició: {anime[-2]}");

'''
+++++++++++++++++++++++++++++++++++
Subcadenes (slicing)
Tasca: Extreure parts d'una cadena
Observació:
Saber fer servir inici:final
+++++++++++++++++++++++++++++++++++
'''
film = "The lord of the rings"

print(f"Extreiem les primeres 4 posicions de la paraula '{film}': {film[0:4]}")
print(f"Extreiem la paraula 'lord' (pos 4 a 8) de la paraula '{film}': {film[4:8]}")
print(f"Mostren la paraula a partir de la posició 12: {film[12:]}")

#Mètodes essencials de les cadenes
'''
+++++++++++++++++++++++++++++++++++
Canvi de format
upper() - Posa el text a majúscules
lower() - Posa el text a minúscules
capitalize() - Primer caràcter en majúscula
title() - Primer caràcter de cada paraula en majúscula
+++++++++++++++++++++++++++++++++++
'''
phrase = " buFaR i fer AmpoLles "

print(f"Frase original: {phrase}")
print(f"Tot majúscules: {phrase.upper()}")
print(f"Tot minúscules: {phrase.lower()}")
print(f"Primer caràcter en majúscula: {phrase.capitalize()}")
print(f"Primer caràcter de cada paraula en majúscula: {phrase.title()}")

'''
+++++++++++++++++++++++++++++++++++
Eliminació i substitució
strip() - Elimina espais de la cadena al principi i al final
replace() - Reemplaça caràcters o text
+++++++++++++++++++++++++++++++++++
'''
print(f"Elimina espais de la cadena al principi i al final:{phrase.strip()}")
print(f"Reemplaça caràcters o text: {phrase.replace("fer","hacer")}")
print(f"Reemplaça caràcters o text: {phrase.replace("A","9")}")

'''
+++++++++++++++++++++++++++++++++++
Cerca i recompte
find() - Retorna la posició on comença la paraula que busquem. -1 si no la troba
count() - Retorna quantes vegades apareix el que caràcter o text que busquem
Operador in - Retorna True o False si la paraula o caràcter està al text que busquem
+++++++++++++++++++++++++++++++++++
'''
frase = "Caga tió, tió de Nadal"
print(f"Retorna la posició on comença la paraula 'tió': {frase.find("tió")}")
print(f"Retorna la posició on comença la paraula 'Nadal': {frase.find("Nadal")}")
print(f"Retorna la posició on comença la paraula 'Marta': {frase.find("Marta")}")

print(f"Retorna quantes vegades apareix la paraula 'tió': {frase.count("tió")}")
print(f"Retorna quantes vegades apareix la lletra 'a': {frase.count("a")}")

if "tió" in frase:
  print("La paraula tió està al text")
else:
  print("La paraula tió NO està al text")

if "Marta" in frase:
  print("La paraula Marta està al text")
else:
  print("La paraula Marta NO està al text")

if "a" in frase:
  print("La lletra a està al text")
else:
  print("La lletra a NO està al text")


#Validació de cadenes
'''
+++++++++++++++++++++++++++++++++++
isalpha() - Si només té lletres
isdigit() - Si només té números
isalnum() - Si és alfanumèrica
" " in text -  Si hi ha espais
+++++++++++++++++++++++++++++++++++
'''
user = "dmoren10"
password = "12345"
secret_message = "El gos s'ha menjat els meus deures"

print(f"El user té només lletres? : {user.isalpha()}")
print(f"El password té només números? : {password.isdigit()}")
print(f"El user té números i lletres? : {user.isalnum()}")

if " " in secret_message:
  print("El missatge conté espais")
else:
  print("El missatge NO conté espais")

#Comparació de cadenes
'''
Tasca: Comparar textos amb ==
Observació: Pyhton distingueix entre minúscules i majúscules
'''
if password == "12345":
  print("Has endevinat el password")
else:
  print("Password incorrecte")

#Recorregut de cadenes nivel SMX

text = "La ment que s'obre a una nova idea, mai torna a la seva mida original."

#Mostrar el text sense el salt de línia del print
for lletra in text:
  print(lletra, end="")

#Fer alguna validació o comprovació en un text
countA = 0

for character in text:
  if character == "a":
    countA += 1

print(f"He trobat {countA} a en el text")

#Mostrar la cadena de text amb accéss positiu i per índex
print("Mostrar la cadena de text amb accéss positiu i per índex")
for i in range(len(text)):
  print(text[i], end="")

#Mostrar la cadena de text amb accéss negatiu
print("\nMostrar la cadena de text amb accéss negatiu")
''' len(text) + 1 -> Afegin 1 valor més a la longitud per incloure l'últim valor

Per exemple si tenim la paraula Hola tenim:

len(Hola) -> 4
4 + 1 = 5 (fem +1 perquè range no inclou l'últim valor)

El bucle va de 1 a 5
A la primera volta si fem -i -> -1 (últim valor) -> a
A la segona volta si fem -i -> - 2 (penúltim valor) -> l
A la tercera volta si fem -i -> - 3 (antepenúltim valor) -> o
A la quarta volta si fem -i -> - 4 (penúltim valor) -> H
'''
for i in range(1, len(text) + 1):
  print(text[-i], end="")